config/routes.rb
Rails.application.routes.draw do

  resources :credits
  resources :votes
  resources :answers
  resources :quizzes

  get 'reports/unique_guests', to: 'reports#unique_guests'
  get 'reports/times_with_more_hits', to: 'reports#times_with_more_hits'
  get 'reports/operating_sistems', to: 'reports#operating_sistems'
  get 'reports/devices', to: 'reports#devices'
  get 'reports/recurring_guests', to: 'reports#recurring_guests'
  get 'reports/registered_users', to: 'reports#registered_users'

  resources :requests
  resources :technical_calls do
    collection do
      get 'open'
    end
  end
  get 'auth/:provider/callback', to: 'guest/login#login_facebook', via: [:get, :post]
  get 'auth/failure', to: redirect('/'), via: [:get, :post]
  get 'signout', to: redirect('/'), via: [:get, :post]

  resources :campaigns do
    collection do
      get 'view'
      get 'votes'
      get 'disable'
      get 'enable'
      post 'disable'
    end
  end

  resources :system_settings, only: [:update] do
    collection do
      get 'my'
    end
  end

  resources :routers
  resources :vouchers do
    collection do
      get 'list'
      delete 'destroy_multiple'
      get 'print'
    end
  end

  get 'users_per_day' => 'charts#users_per_day'
  get 'last_campaign' => 'charts#last_campaign'
  get 'vouchers_use' => 'charts#vouchers_use'

  resources :users do
    collection do
      post 'destroy_multiple'
      get 'active'
      get 'listmac'
      get 'listprofile'
      get 'removemac'
      get 'removeprofile'
      get 'remove'
      get 'verify_whatsapp'
      get 'verify_email'
      post 'addmac'
      post 'addprofile'
      get 'guest_cadastro'
      post 'create_guest'
      get 'forgot_password'
      post 'change_password'
      get 'export'
      post 'api_voucher'
    end
  end

  resources :admins do
    collection do
      get 'clients'
      get 'new_client'
      delete 'destroy_multiple'
    end
    member do
      get 'credit_history'
    end
  end

  devise_for :admins, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  get 'home/index'
  get 'home/clients'
  get 'home/list_aps'
  post 'home/list_aps'
  get 'home/top_users'

  namespace :guest do

    post 'auth' => 'login#auth'
    post 'comerciarios' => 'login#comerciarios'
    post 'hospedes' => 'login#hospedes'
    post 'geral' => 'login#geral'
    post 'giraffas' => 'login#giraffas'

    post 'caldas_cpf' => 'login#caldas_cpf'
    post 'create_api_caldas' => 'login#create_api_caldas'
    post 'create_api_atalaia' => 'login#create_api_atalaia'
    post 'api_convidados' => 'login#api_convidados'
    post 'api_voucher' => 'login#api_voucher'

    post 'cadgiraffas' => 'login#cadgiraffas'
    post 'riovermelhocorp' => 'login#riovermelhocorp'

    get 'corporativo' => 'login#indexcorp'
    get 'cpf' => 'login#cpf'
    get 'caldas' => 'login#caldas'

    get 'novo' => 'login#novo'
    get 'pspr' => 'login#pspr'
    get 'novo_login_facebook' => 'login#novo_login_facebook'
    post 'novo_login' => 'login#novo_login'
    post 'novo_login_pspr' => 'login#novo_login_pspr'

    root 'login#novo'
  end

  namespace :api do
    namespace :v1 do
      get 'campagins' => 'auth#campaigns'
      get 'quiz' => 'auth#quiz'
      get 'answers' => 'auth#answers'
      get 'votes' => 'auth#votes'
      get 'connect' => 'auth#connect'
    end
  end

  root :to => "home#index"

end

app/views/admins/_form.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
            <%- model_class = Admin -%>
                <%=t '.title', :default => [:'helpers.titles.new', '%{model}'], :model => model_class.model_name.human.titleize %>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">

					 <%= simple_form_for(@admin) do |f| %>


                            <%= f.input :name %>
                            <%= f.input :phone %>
                            <%= f.input :cpf_cnpj %>
                            <%= f.input :email %>
                            <%= f.input :password %>

                            

                            <%= f.input :role, as: :radio_buttons, collection: [['cliente', ' Cliente'], ['administrador', ' Administrador']], label_method: :second, value_method: :first %>

                           

                            <%= f.button :submit, :class => 'btn-primary' %>
                          <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                                        admins_path, :class => 'btn btn-default' %>

					<% end %>

					</div>

                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

app/views/admins/clients.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
              <%- model_class = Admin -%>
              Clientes
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">


          <div class="table-responsive col-lg-12">

              <table class="table table-striped table-bordered table-hover" id="dynamic-table">
                  <thead>
                      <tr>
                         <tr>
                            <th><%= model_class.human_attribute_name(:id) %></th>
                            <th>Nome</th>
                            <th><%= model_class.human_attribute_name(:email) %></th>
                            <th>Créditos</th>

                            <th><%=t '.actions', :default => t("Ação") %></th>
                          </tr>
                      </tr>
                  </thead>
                  <tbody>
                     <% @admins.each do |admin| %>
                        <tr>
                          <td><%= link_to admin.id, admin_path(admin) %></td>
                          <td><%= admin.name %></td>
                          <td><%= admin.email %></td>
                          <td><%= admin.credit %></td>

                          <td>
                          <div class="btn-group pull-right ">
                            <%= link_to 'Adicionar créditos', new_credit_path(admin_id: admin.id), class: 'btn btn-success btn-sm' %>
                            <%= link_to 'Histórico créditos', credit_history_admin_path(admin), class: 'btn btn-default btn-sm' %>
                            <%= link_to t('.edit', :default => t("Editar")), edit_admin_path(admin), :class => 'btn btn-default btn-sm' %>
                            <%= link_to t('.destroy', :default => t("Excluir")),
                                        admin_path(admin),
                                        :method => :delete,
                                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Tem certeza?')) },
                                        :class => 'btn btn-sm btn-danger' %>


                          </div>
                          </td>
                        </tr>
                      <% end %>

                  </tbody>
              </table>
          </div>
          <!-- /.table-responsive -->
          <div class="col-lg-12">
            <%= link_to t('.new', :default => t("Criar cliente")),
            new_client_admins_path,
            :class => 'btn btn-primary pull-right' %>
          </div>
        </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>
<!-- /.row -->

app/views/admins/credit_history.html.erb
<div class="row">
  <div class="col-xs-12">

    <section class="panel">
      <div class="panel-heading">
        Histórico de lançamento de crédito - <%= @admin.name %>
      </div>

      <div class="panel-body">
        <div class="row">
          <div class="col-xs-12">
            <table class="table table-striped table-bordered table-hover" id="dynamic-table">
              <thead>
                <tr>
                  <th>Quantidade</th>
                  <th>Data</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                <% @admin.credits.each do |credit| %>
                  <tr>
                    <td><%= credit.amount %></td>
                    <td><%= credit.created_at.strftime("%d/%m/%Y %H:%M") %></td>
                    <td><%= link_to 'Excluir', credit, method: :delete, data: { confirm: 'A quantidade de créditos será descrescida do saldo do cliente. Esta ação não pode ser desfeita. Tem certeza que deseja excluir?' }, class: 'btn btn-danger btn-sm' %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <div class="col-xs-12">
            <%= link_to 'Editar Campanha', edit_campaign_path(@admin), class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    </section>

  </div>
</div>

app/views/admins/edit.html.erb
<%= render 'form' %>

app/views/admins/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
              <%- model_class = Admin -%>
              <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">


          <div class="table-responsive col-lg-12">

              <table class="table table-striped table-bordered table-hover" id="dynamic-table">
                  <thead>
                      <tr>
                         <tr>
                            <th><%= model_class.human_attribute_name(:id) %></th>
                            <th><%= model_class.human_attribute_name(:email) %></th>

                            <th><%=t '.actions', :default => t("Ação") %></th>
                          </tr>
                      </tr>
                  </thead>
                  <tbody>
                     <% @admins.each do |admin| %>
                        <tr>
                          <td><%= link_to admin.id, admin_path(admin) %></td>
                          <td><%= admin.email %></td>

                          <td>
                          <div class="btn-group pull-right ">
                            <%= link_to t('.edit', :default => t("Editar")), edit_admin_path(admin), :class => 'btn btn-default btn-sm' %>
                            <%= link_to t('.destroy', :default => t("Excluir")),
                                        admin_path(admin),
                                        :method => :delete,
                                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Tem certeza?')) },
                                        :class => 'btn btn-sm btn-danger' %>


                          </div>
                          </td>
                        </tr>
                      <% end %>

                  </tbody>
              </table>
          </div>
          <!-- /.table-responsive -->
          <div class="col-lg-12">
            <%= link_to t('.new', :default => t("Criar usuário")),
            new_admin_path,
            :class => 'btn btn-primary pull-right' %>
          </div>
        </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>
<!-- /.row -->

app/views/admins/new.html.erb
<%= render 'form' %>

app/views/admins/new_client.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
            <%- model_class = Admin -%>
                <%=t '.title', :default => [:'helpers.titles.new', '%{model}'], :model => model_class.model_name.human.titleize %>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">

           <%= simple_form_for(@admin) do |f| %>


                            <%= f.input :name %>
                            <%= f.input :phone %>
                            <%= f.input :cpf_cnpj %>
                            <%= f.input :email %>
                            <%= f.input :password %>

                            <%= f.input :role, input_html: { value: 'cliente'}, as: :hidden %>

                            <%= f.button :submit, :class => 'btn-primary' %>
                          <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                                        admins_path, :class => 'btn btn-default' %>

          <% end %>

          </div>

                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

app/views/admins/show.html.erb
<%= link_to 'Edit', edit_loger_path(@loger) %> |
<%= link_to 'Back', logers_path %>