config/routes.rb
Rails.application.routes.draw do

  resources :credits
  resources :votes
  resources :answers
  resources :quizzes

  get 'reports/unique_guests', to: 'reports#unique_guests'
  get 'reports/times_with_more_hits', to: 'reports#times_with_more_hits'
  get 'reports/operating_sistems', to: 'reports#operating_sistems'
  get 'reports/devices', to: 'reports#devices'
  get 'reports/recurring_guests', to: 'reports#recurring_guests'
  get 'reports/registered_users', to: 'reports#registered_users'

  resources :requests
  resources :technical_calls do
    collection do
      get 'open'
    end
  end
  get 'auth/:provider/callback', to: 'guest/login#login_facebook', via: [:get, :post]
  get 'auth/failure', to: redirect('/'), via: [:get, :post]
  get 'signout', to: redirect('/'), via: [:get, :post]

  resources :campaigns do
    collection do
      get 'view'
      get 'votes'
      get 'disable'
      get 'enable'
      post 'disable'
    end
  end

  resources :system_settings, only: [:update] do
    collection do
      get 'my'
    end
  end

  resources :routers
  resources :vouchers do
    collection do
      get 'list'
      delete 'destroy_multiple'
      get 'print'
    end
  end

  get 'users_per_day' => 'charts#users_per_day'
  get 'last_campaign' => 'charts#last_campaign'
  get 'vouchers_use' => 'charts#vouchers_use'

  resources :users do
    collection do
      post 'destroy_multiple'
      get 'active'
      get 'listmac'
      get 'listprofile'
      get 'removemac'
      get 'removeprofile'
      get 'remove'
      get 'verify_whatsapp'
      get 'verify_email'
      post 'addmac'
      post 'addprofile'
      get 'guest_cadastro'
      post 'create_guest'
      get 'forgot_password'
      post 'change_password'
      get 'export'
      post 'api_voucher'
    end
  end

  resources :admins do
    collection do
      get 'clients'
      get 'new_client'
      delete 'destroy_multiple'
    end
    member do
      get 'credit_history'
    end
  end

  devise_for :admins, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  get 'home/index'
  get 'home/clients'
  get 'home/list_aps'
  post 'home/list_aps'
  get 'home/top_users'

  namespace :guest do

    post 'auth' => 'login#auth'
    post 'comerciarios' => 'login#comerciarios'
    post 'hospedes' => 'login#hospedes'
    post 'geral' => 'login#geral'
    post 'giraffas' => 'login#giraffas'

    post 'caldas_cpf' => 'login#caldas_cpf'
    post 'create_api_caldas' => 'login#create_api_caldas'
    post 'create_api_atalaia' => 'login#create_api_atalaia'
    post 'api_convidados' => 'login#api_convidados'
    post 'api_voucher' => 'login#api_voucher'

    post 'cadgiraffas' => 'login#cadgiraffas'
    post 'riovermelhocorp' => 'login#riovermelhocorp'

    get 'corporativo' => 'login#indexcorp'
    get 'cpf' => 'login#cpf'
    get 'caldas' => 'login#caldas'

    get 'novo' => 'login#novo'
    get 'pspr' => 'login#pspr'
    get 'novo_login_facebook' => 'login#novo_login_facebook'
    post 'novo_login' => 'login#novo_login'
    post 'novo_login_pspr' => 'login#novo_login_pspr'

    root 'login#novo'
  end

  namespace :api do
    namespace :v1 do
      get 'campagins' => 'auth#campaigns'
      get 'quiz' => 'auth#quiz'
      get 'answers' => 'auth#answers'
      get 'votes' => 'auth#votes'
      get 'connect' => 'auth#connect'
    end
  end

  root :to => "home#index"

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
    mount_uploader :imagem, CampaignImageUploader
    has_and_belongs_to_many :routers
    has_many :requests
    belongs_to :quiz
    belongs_to :admin

    after_create :decrease_credits_from_client_on_create
    after_update :decrease_credits_from_client_on_update

    scope :date_valid, lambda {where("stard_date <= ? AND end_date >= ?", Date.today, Date.today )}

    validates_presence_of :weight, :name, :stard_date, :end_date, :admin_id
    validates :credits, numericality: { greater_than_or_equal_to: 0 }

    validate :credits_availability

    def credits_difference
      if self.credits_was.nil?
        self.credits
      else
        self.credits - self.credits_was
      end
    end

    # Usado ao mostra a campanha
    def decrease_credit
      self.update_column(:credits, self.credits - 1)
    end

    private
      def decrease_credits_from_client_on_create
        self.admin.credit -= self.credits
        self.admin.save
      end

      def decrease_credits_from_client_on_update
        self.admin.credit -= self.credits_difference
        self.admin.save
      end

      def credits_availability
        self.errors[:credits] << "Créditos insuficiêntes. Saldo disponível: #{self.admin.credit}." unless self.credits_difference <= self.admin.credit
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin!, except: [:guest_cadastro, :create_guest, :forgot_password, :change_password]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  before_action :load_settings, only: [:guest_cadastro, :create_guest]

  # GET /users
  # GET /users.json
  def index

    @filterrific = initialize_filterrific(
        User,
        params[:filterrific],
        default_filter_params: {},
        sanitize_params: true,
    ) || return
    @users = @filterrific.find.page(params[:page]).order(created_at: :desc)

    respond_to do |format|
      format.html
      format.js
    end

  end


  def verify_whatsapp

    @user = User.find(params[:token])

    respond_to do |format|
      if @user.update(whatsapp_verified: true)
        format.html { render :text => "OK" }
        # format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        # format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def verify_email

    @user = User.find(params[:token])

    respond_to do |format|
      if @user.update(email_verified: true)
        format.html { render :text => "OK" }
        # format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        # format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def active
    @usuarios = Array.new

    # Router.all.each do |router|
    router = Router.first

      ip = router.ip_out
      port = router.port_out
      username = router.username
      password = router.password
      check = Net::Ping::External.new(router.ip_out)
      puts "ROUTER #{router.ip_out}".on_yellow
      if check.ping?
        puts "PINGOU ROUTER #{router.ip_out}".on_yellow
         begin
        tik = MTik::Connection.new(:host => ip, :user => username, :pass => password, :port => port)
         rescue MTik::Error, Errno::ETIMEDOUT, Errno::EHOSTUNREACH, Errno::ECONNREFUSED => e
           print "ERROR CONNECTING OR LOGGING IN: #{e}\n"
          #  next
         end

        @users = {}
        tik.get_reply_each('/ip/hotspot/active/getall') do |r, s|
          if s.key?('!re') && s.key?('.id')
            @users[s['.id']] = {
                :address => s['address'],
                :user => s['user'],
                :comment => s['comment'],
                :server => s['server'],
                :uptime => s['uptime'],
                :macaddress => s['mac-address'],
                :disabled => s['disabled'] == true,
                :id => s['.id']
            }
          end
        end

        tik.close
        @users.each { |hotspot_user| @usuarios << hotspot_user[1] }

        puts "FEITA REQUISIÂO ROUTER #{router.location}".on_yellow
      end

    # end

    respond_to do |format|
      format.html { render :active }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show

    @user = User.find(params[:id])

    array = Request.where(user_id: @user.id).group(:location).count

    @series = [{name: "Recorrência", data: array}]

    @graph = array.map do |n, i|
      {
          name: n,
          data: i
      }
    end
    @requests_total = Request.where(user_id: @user.id).count

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /users/new
  def new
    @user = User.new

    notice = nil

    router = Router.first

    ip = router.ip_out
    port = router.port_out
    username = router.username
    password = router.password

    begin
      tik = MTik::Connection.new(:host => ip, :user => username, :pass => password, :port => port)
    rescue MTik::Error, Errno::ETIMEDOUT, Errno::EHOSTUNREACH, Errno::ECONNREFUSED => e
      print "ERROR CONNECTING OR LOGGING IN: #{e}\n"
      exit
    end

    @profiles = {}
    tik.get_reply_each('/ip/hotspot/user/profile/getall') do |r, s|


      if s.key?('!re') && s.key?('.id')
        @profiles[s['.id']] = {
            :name => s['name'],
            :sessiontimeout => s['session-timeout'],
            :sharedusers => s['shared-users'],
            :ratelimit => s['rate-limit'],
            :id => s['.id']
        }
      end

    end

    # puts @profiles

    @perfis = Array.new
    @profiles.each { |profile| @perfis << profile[1] }
    tik.close
  end

  def guest_cadastro

    @user = User.find_by(mac: session[:mac])
    if @user.present?
      if @user.connections.nil?
        @user.connections = 0
        @user.update(connections: @user.connections + 1)
        @user.macs.create(mac: session[:mac]) unless @usuario.macs.find_by(mac: session[:mac])
      else
        @user.update(connections: @user.connections + 1)
        @user.macs.create(mac: session[:mac]) unless @usuario.macs.find_by(mac: session[:mac])
      end
    else
      @user = User.new(
        email: params[:email],
        name: params[:name]
      )

      @user.profile = 'default'
      notice = nil
    end
    
  end

  def create_guest

    router = Router.find_by_location(session[:location])

    ip = router.ip_out
    port = router.port_out
    username = router.username
    password = router.password

    @user = User.find_by(mac: session[:mac])
    @user = User.find_by(name: params[:name]) unless @user.present?

    if @user.present?
      if @user.connections.nil?
        @user.connections = 0
        @user.update(connections: @user.connections + 1)
        @user.macs.create(mac: session[:mac]) unless @usuario.macs.find_by(mac: session[:mac])
      else
        @user.update(connections: @user.connections + 1)
      end
      respond_to do |format|
        format.html { redirect_to "http://#{router.ip}/login?username=admin&password=admin" }
      end
    else
      @user = User.new(user_params)

      @user.mac = session[:mac]

      respond_to do |format|
        if @user.save
          format.html { redirect_to "http://#{router.ip}/login?username=admin&password=admin" }
        else
          format.html { render :guest_cadastro }
        end
        # end
        # tik.close
      end
    end

    

  end


  def forgot_password

  end

  def change_password
    user = User.find_by_cpf(params[:cpf].gsub(/\D/, ''))

    if user.present? and user.date == Date.parse(params[:date]) and params[:new_password].present?
      user.update(password: params[:new_password])
      redirect_to guest_root_path, alert: "Senha alterada com sucesso! Faça o login com sua nova senha."
    else
      redirect_to forgot_password_users_path, alert: "As informações não conferem, verifique e tente novamente!"
    end
  end

  # GET /users/1/edit
  def edit

  end

  def destroy_multiple

    User.destroy(params[:users])

    respond_to do |format|
      format.html { redirect_to users_path }
      format.json { head :no_content }
    end

  end

  # POST /users
  # POST /users.json
  def create

    Router.all.each do |router|

      ip = router.ip_out
      port = router.port_out
      username = router.username
      password = router.password


      @user = User.new(user_params)
      @user.email = @user.email.downcase
      @user.password = @user.password.downcase


      begin
        tik = MTik::Connection.new(:host => ip, :user => username, :pass => password, :port => port)
        puts "COMUNICOU COM O ROUTER #{router.location}".on_yellow
      rescue MTik::Error, Errno::ETIMEDOUT, Errno::EHOSTUNREACH, Errno::ECONNREFUSED => e
        print "ERROR CONNECTING OR LOGGING IN: #{e}\n"
      end
      tik.get_reply(
          "/ip/hotspot/user/add", "=name=#{@user.email}", "=password=#{@user.password}", "=profile=#{@user.profile}"
      )
      tik.close

    end

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'Usuario criado com sucesso.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { redirect_to new_user_path, notice: 'Erro ao criar usuário, pode ser que o mesmo já exista.' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end

  # APARENTEMENTE SEM USO
  def remove

    router = Router.first

    ip = router.ip_out
    port = router.port_out
    username = router.username
    password = router.password

    begin
      tik = MTik::Connection.new(:host => ip, :user => username, :pass => password, :port => port)
    rescue MTik::Error, Errno::ETIMEDOUT, Errno::EHOSTUNREACH, Errno::ECONNREFUSED => e
      print "ERROR CONNECTING OR LOGGING IN: #{e}\n"
      # exit
    end

    users = {}
    tik.get_reply_each('/ip/hotspot/active/getall') do |r, s|
      if s.key?('!re') && s.key?('mac-address')
        users[s['mac-address']] = {
            :macaddress => s['mac-address'],
            :id => s['.id']
        }
      end
    end


    username = params[:username]
    id = users["#{username}"][:id]
    teste = tik.get_reply('/ip/hotspot/active/remove', "=.id=#{id}") if users.key?("#{username}")

    users = {}
    tik.get_reply_each('/ip/hotspot/cookie/getall') do |r, s|
      if s.key?('!re') && s.key?('mac-address')
        users[s['mac-address']] = {
            :macaddress => s['mac-address'],
            :id => s['.id']
        }
      end
    end

    username = params[:username]
    id = users["#{username}"][:id]
    teste = tik.get_reply('/ip/hotspot/cookie/remove', "=.id=#{id}") if users.key?("#{username}")

    tik.close
    respond_to do |format|
      format.html { redirect_to active_users_path }
    end


  end

  def addmac
    router = Router.find(params[:router_id])

    ip = router.ip_out
    port = router.port_out
    username = router.username
    password = router.password

    begin
      tik = MTik::Connection.new(:host => ip, :user => username, :pass => password, :port => port)
    rescue MTik::Error, Errno::ETIMEDOUT, Errno::EHOSTUNREACH, Errno::ECONNREFUSED, Errno::ENETUNREACH => e

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_addmac.js.erb
ok

app/views/users/_form.html.erb
<p id="notice" style="color: red;"><%= notice %></p>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
            <%- model_class = User -%>
                <%=t '.title', :default => [:'helpers.titles.new', '%{model}'], :model => model_class.model_name.human.titleize %>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">


                        <%= simple_form_for @user, html: { class: 'form-horizontal' }, wrapper: :horizontal_form do |f|%>


                            <%= f.input :name %>
                            <%= f.input :email %>
                            <%= f.input :telephone %>
                            <%= f.input :cpf %>
                            <%= f.input :date, as: :string %>

                            <%= f.input :password %>
                            <div class="form-group profile optional user_profile">
                              <label class="col-sm-3 control-label profile" for="user_telephone">Perfil</label>
                              <div class="col-sm-9">
                                  <%- #f.select(:profile, @perfis.map { |value| [ value[:name], value[:name]]}, {}, { :class => 'form-control' }) %>
                              </div>
                            </div>
                            <%= f.button :submit, :class => 'btn-primary' %>
                            <%= link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn btn-default' %>

                        <% end %>
                    </div>

                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

app/views/users/_list.html.erb
<script type="text/javascript">
    function checkAll(check_all) {

        var inputs = check_all.form.getElementsByTagName("input");
        for (var i = 0; i < inputs.length; i++) {
            // Only work on checkboxes, and NOT on the "Check All" checkbox
            if (inputs[i].type == "checkbox" && inputs[i].name != check_all.name) {
                if (check_all.checked == true) {
                    inputs[i].checked = true;
                } else {
                    inputs[i].checked = false;
                }
            }
        }
    }
</script>

<!-- /.row -->

<%= form_tag destroy_multiple_users_path, method: :delete do %>
  <div id="filterrific_results">
    <div class="row">
      <div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-heading">

            <%- model_class = User -%>
            <%= t '.title', :default => model_class.model_name.human.pluralize.titleize %>
          </div>
          <!-- /.panel-heading -->
          <div class="panel-body">
            <table class="table table-striped table-bordered table-hover">
              <thead>
              <tr>
              <tr>
                <th><%= check_box_tag('check_all', 'check_all', false, :onClick => "checkAll(this);") %></th>
                <th><%= model_class.human_attribute_name(:id) %></th>
                <th><%= model_class.human_attribute_name(:name) %></th>
                <th><%= model_class.human_attribute_name(:email) %></th>
                <th><%= model_class.human_attribute_name(:telephone) %></th>
                
           

                <th><%= t '.actions', :default => t("Ação") %></th>
              </tr>
              </tr>
              </thead>
              <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td><%= check_box_tag "users[]", user.try(:id) %></td>
                  <td><%= link_to user.id, user_path(user), remote: true %></td>


                  <td><%= user.try(:name) %></td>
                  <td><%= user.try(:email) %></td>
                  <td><%= user.try(:telephone) %></td>
              
                  
                    <td>
                      <div class="btn-group pull-right ">
                        <%= link_to 'Ver', user_path(user), remote: true, :class => 'btn btn-primary btn-sm' %>
                        <%= link_to t('.edit', :default => t("Editar")), edit_user_path(user), :class => 'btn btn-warning btn-sm' %>
                        <%= link_to t('.destroy', :default => t("Excluir")),
                                    user_path(user),
                                    :method => :delete,
                                    :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Tem certeza?'))},
                                    :class => 'btn btn-sm btn-danger' %>


                      </div>

                    </td>
                    </tr>
              <% end %>

              </tbody>
            </table>
            <div class="col-lg-12">
              <% #link_to t('.new', :default => t("Criar usuário")), new_user_path, :class => 'btn btn-primary pull-right' %>
            </div><%= paginate @users, :theme => 'twitter-bootstrap-3' %>
          </div>


<% end %>

</div>
<!-- /.panel-body -->
</div>
<!-- /.panel -->
</div>
<!-- /.col-lg-6 -->
</div>
<!-- /.row -->

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/forgot_password.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <% flash.each do |key, value| %>
        <div class="alert alert-danger" role="alert">
          <span class="fa fa-warning" aria-hidden="true"></span>
          <a href="#" data-dismiss="alert" class="close">×</a>
          <span class="sr-only">Erro:</span>
          <%= value %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Resetar senha</h1>
      <%= form_tag change_password_users_path, method: :post do %>
        <div class="row">
          <div class="form-group col-xs-12">
            <%= label_tag 'CPF' %>
            <%= text_field_tag :cpf, '', class: 'form-control' %>
          </div>
          <div class="form-group col-xs-12">
            <%= label_tag 'Data de nascimento' %>
            <%= text_field_tag :date, '', class: 'form-control', id: 'date' %>
          </div>
          <div class="form-group col-xs-12">
            <%= label_tag 'Nova Senha' %>
            <%= password_field_tag :new_password, '', class: 'form-control' %>
          </div>
          <div class="col-xs-3">
            <%= submit_tag 'Filtrar', class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>


<script>
  $( function() {
    $("#date").datetimepicker({
      format: 'DD/MM/YYYY'
    });
  });
</script>

app/views/users/guest_cadastro.html.erb
<style>
  #login-logo{
    margin-bottom: 1em;
    padding: 1em;
  }

  #container-login{
    background-image: url(<%= image_url (@system_setting.background.present? ? @system_setting.background : 'bg.png') %>);
    height: 100vh;
    background-size: cover;
  }
</style>
<div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-danger" role="alert">
        <span class="fa fa-warning" aria-hidden="true"></span>
        <a href="#" data-dismiss="alert" class="close">×</a>
        <span class="sr-only">Erro:</span>
        <%= value %>
      </div>
    <% end %>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                <%- model_class = User -%>
                    <%=t '.title', :default => [:'helpers.titles.new', '%{model}'], :model => model_class.model_name.human.titleize %>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="alert alert-danger" role="alert">
                                <span class="fa fa-warning" aria-hidden="true"></span>
                                <a href="#" data-dismiss="alert" class="close">×</a>
                                <span class="sr-only"></span>
                                Você precisa cadastrar este quipamento: <strong><%= session[:mac] %></strong>
                              </div>


                          <%= image_tag (@system_setting.logo.present? ? @system_setting.logo : 'dotspot.png'), class: 'img-responsive center-block', id: 'login-logo' %>
                            <%= simple_form_for @user, html: { class: 'form-horizontal', onsubmit: 'return validateForm();' }, wrapper: :horizontal_form, :url => create_guest_users_url, :method => :post do |f|%>

                                <%= f.input :name, placeholder: '', required: true if @system_setting.name_visible? %>
                                <%= f.input :email if @system_setting.email_visible? %>
                                <%= f.input :telephone if @system_setting.telephone_visible? %>
                                <%= f.input :gender, collection: ['Masculino', 'Feminino'] if @system_setting.gender_visible? %>
                                <%= f.input :date, as: :string if @system_setting.birthday_visible? %>
                                <%= f.input :cpf, input_html: { type: 'number'}, label: 'CPF (somente números)' if @system_setting.cpf_visible? %>
                                <%= f.input :address if @system_setting.address_visible? %>
                                <%= f.input :number if @system_setting.address_visible? %>
                                <%= f.input :city if @system_setting.address_visible? %>
                                <%= f.input :district if @system_setting.address_visible? %>
                                <%= f.input :state if @system_setting.address_visible? %>

                                <%- # f.input :password, hint: "Deve ter 6 ou mais caracteres e conter pelo menos 1 número e 1 letra " %>

                                <%= f.button :submit, 'Cadastrar e Conectar', :class => 'btn btn-lg btn-primary', id:'submit_btn'%>
                                <hr>
                             
                                <%#= link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn btn-default' %>

                            <% end %>
                        </div>

                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>

</div>

<script>
  $( function() {
    $("#user_date").datetimepicker({
      format: 'DD/MM/YYYY'
    });
  });


  function validateForm(){

    var validade_msg = "";

    <% if @system_setting.cpf_required? %>

    if(!CPF.validate($("#user_cpf").val())){
      validade_msg += "· O CPF digitado\n";
    }

    <% end %>

    <% if @system_setting.email_required? %>

    if(!validateEmail($("#user_email").val())){
      validade_msg += "· O email digitado\n";
    }

    <% end %>

    // if(!validatePassword()){
    //   validade_msg += "· A senha digitada\n";
    // }

    if(validade_msg.length > 0){
      alert("A validação falhou, varifique: \n\n" + validade_msg);
      return false;
    }else{
      return true;
    }
  }

  function validateEmail(email){
    var re = /[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/;
    regex_valid =  re.test(email);

    if(regex_valid && isNotTempmail(email)){
      return true
    }else{
      return false
    }

  }

  // function validatePassword(){
  //   if($('#user_password').val().length >= 6){
  //     return true
  //   }
  //   return false
  // }

  function isNotTempmail(email){
    var validation = true;
    var tempList = [
      'emailtemporario.com.br',
      'getairmail.com',
      'guerrillamail.com',
      'meltmail.com',
      '10minutemail.com',
      'jetable.org',
      'spammotel.com',
      'mailexpire.com',
      'mytrashmail.com',
      'maillinator.com',
      'temp-mail.org',
      'yopmail.com',
      'fakeinbox.com',
      'sharklasers.com',
      'dropmail.me',
      'dispostable.com',
      'mailnesia.com',
      '20minutemail.com',
      'deadaddress.com',
      'emailsensei.com',
      'filzmail.com',
      'incognomail.com',
      'koszmail.pl',
      'mailcatch.com',
      'noclickmail.com',
      'spamfree24.org',
      'trashmail.ws',
      'stop-my-spam.com'
    ]

    tempList.forEach((item) => {
      if(email.includes(item)) validation = false;
    })

    return validation
  }

</script>

app/views/users/index.html.erb
<%= form_for_filterrific @filterrific do |f| %>
  <div>
    Buscar:
    <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
    <%= f.text_field(
      :search_query,
      class: 'filterrific-periodically-observed form-control medium'
    ) %>
  </div>
  <br>
  <br>
  <%# add an automated spinner to your form when the list is refreshed %>
  <%= render_filterrific_spinner %>
<% end %>


<%= render(
  partial: 'list',
  locals: { users: @users }
) %>


<div id='user-content'></div>

<%= link_to 'Exportar todos os contatos em excel', reports_registered_users_path(format: 'xlsx'), class: 'btn btn-success btn-rounded'%>

app/views/users/index.js.erb
<% js = escape_javascript(
  render(partial: 'list', locals: { users: @users })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Category:</strong>
  <%= @user.category %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Number:</strong>
  <%= @user.number %>
</p>

<p>
  <strong>City:</strong>
  <%= @user.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @user.state %>
</p>

<p>
  <strong>District:</strong>
  <%= @user.district %>
</p>

<p>
  <strong>Code:</strong>
  <%= @user.code %>
</p>

<p>
  <strong>Registry:</strong>
  <%= @user.registry %>
</p>

<p>
  <strong>Issuing:</strong>
  <%= @user.issuing %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @user.cpf %>
</p>

<p>
  <strong>Date:</strong>
  <%= @user.date %>
</p>

<p>
  <strong>Validate:</strong>
  <%= @user.validate %>
</p>

<p>
  <strong>Registration:</strong>
  <%= @user.registration %>
</p>

<p>
  <strong>Company:</strong>
  <%= @user.company %>
</p>

<p>
  <strong>Depend:</strong>
  <%= @user.depend %>
</p>

<p>
  <strong>Dependent:</strong>
  <%= @user.dependent %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>