config/routes.rb
Rails.application.routes.draw do

  resources :credits
  resources :votes
  resources :answers
  resources :quizzes

  get 'reports/unique_guests', to: 'reports#unique_guests'
  get 'reports/times_with_more_hits', to: 'reports#times_with_more_hits'
  get 'reports/operating_sistems', to: 'reports#operating_sistems'
  get 'reports/devices', to: 'reports#devices'
  get 'reports/recurring_guests', to: 'reports#recurring_guests'
  get 'reports/registered_users', to: 'reports#registered_users'

  resources :requests
  resources :technical_calls do
    collection do
      get 'open'
    end
  end
  get 'auth/:provider/callback', to: 'guest/login#login_facebook', via: [:get, :post]
  get 'auth/failure', to: redirect('/'), via: [:get, :post]
  get 'signout', to: redirect('/'), via: [:get, :post]

  resources :campaigns do
    collection do
      get 'view'
      get 'votes'
      get 'disable'
      get 'enable'
      post 'disable'
    end
  end

  resources :system_settings, only: [:update] do
    collection do
      get 'my'
    end
  end

  resources :routers
  resources :vouchers do
    collection do
      get 'list'
      delete 'destroy_multiple'
      get 'print'
    end
  end

  get 'users_per_day' => 'charts#users_per_day'
  get 'last_campaign' => 'charts#last_campaign'
  get 'vouchers_use' => 'charts#vouchers_use'

  resources :users do
    collection do
      post 'destroy_multiple'
      get 'active'
      get 'listmac'
      get 'listprofile'
      get 'removemac'
      get 'removeprofile'
      get 'remove'
      get 'verify_whatsapp'
      get 'verify_email'
      post 'addmac'
      post 'addprofile'
      get 'guest_cadastro'
      post 'create_guest'
      get 'forgot_password'
      post 'change_password'
      get 'export'
      post 'api_voucher'
    end
  end

  resources :admins do
    collection do
      get 'clients'
      get 'new_client'
      delete 'destroy_multiple'
    end
    member do
      get 'credit_history'
    end
  end

  devise_for :admins, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  get 'home/index'
  get 'home/clients'
  get 'home/list_aps'
  post 'home/list_aps'
  get 'home/top_users'

  namespace :guest do

    post 'auth' => 'login#auth'
    post 'comerciarios' => 'login#comerciarios'
    post 'hospedes' => 'login#hospedes'
    post 'geral' => 'login#geral'
    post 'giraffas' => 'login#giraffas'

    post 'caldas_cpf' => 'login#caldas_cpf'
    post 'create_api_caldas' => 'login#create_api_caldas'
    post 'create_api_atalaia' => 'login#create_api_atalaia'
    post 'api_convidados' => 'login#api_convidados'
    post 'api_voucher' => 'login#api_voucher'

    post 'cadgiraffas' => 'login#cadgiraffas'
    post 'riovermelhocorp' => 'login#riovermelhocorp'

    get 'corporativo' => 'login#indexcorp'
    get 'cpf' => 'login#cpf'
    get 'caldas' => 'login#caldas'

    get 'novo' => 'login#novo'
    get 'pspr' => 'login#pspr'
    get 'novo_login_facebook' => 'login#novo_login_facebook'
    post 'novo_login' => 'login#novo_login'
    post 'novo_login_pspr' => 'login#novo_login_pspr'

    root 'login#novo'
  end

  namespace :api do
    namespace :v1 do
      get 'campagins' => 'auth#campaigns'
      get 'quiz' => 'auth#quiz'
      get 'answers' => 'auth#answers'
      get 'votes' => 'auth#votes'
      get 'connect' => 'auth#connect'
    end
  end

  root :to => "home#index"

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_dates
#  load_and_authorize_resource
  def unique_guests
    if has_date?
      @requests = Request.where(created_at: @start_date..@end_date).page(params[:page])
      @graph = Request.where(created_at: @start_date..@end_date).group_by_day(:created_at, format: "%d/%m/%Y").count
    else
      @requests = Request.all.page(params[:page])
      @graph = Request.all.group_by_month(:created_at, format: "%d/%m/%Y").count
    end

    respond_to do |format|
      format.html
      format.csv { send_data @requests.to_csv }
    end
  end

  def recurring_guests
 
    @usuarios = User.where("connections >= 0").order(connections: :desc).page(params[:page]).per(15)
    respond_to do |format|
      format.html
      format.csv { send_data @usuarios.to_csv }
    end
  end

  def registered_users
    @users = User.all.order(id: :desc)
    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  def times_with_more_hits
    if has_date?
      @requests = Request.where(created_at: @start_date..@end_date).group_by_hour(:created_at, format: "%Hh").count
    else
      @requests = Request.all.group_by_hour(:created_at, format: "%Hh").count
    end
    respond_to do |format|
      format.html
      format.csv { send_data Request.generate_csv(@requests, ['Time', 'Quantity']) }
    end
  end

  def operating_sistems
    if has_date?
      @requests = Request.where(created_at: @start_date..@end_date).group(:platform).count
    else
      @requests = Request.all.group(:platform).count
    end

    @devices = count_sistems @requests

    respond_to do |format|
      format.html
      format.csv { send_data Request.generate_csv(@requests, ['Platform', 'Quantity']) }
    end
  end

  def devices
    if has_date_and_campaign?
      @requests = Request.where(created_at: @start_date..@end_date).where(campaign_id: params[:campaign]).group(:platform).count
      @requests_location = Request.where(created_at: @start_date..@end_date).where(campaign_id: params[:campaign]).group(:location).count
      @requests_total = Request.where(created_at: @start_date..@end_date).where(campaign_id: params[:campaign]).count
      @request_male = Request.where(created_at: @start_date..@end_date).where(campaign_id: params[:campaign]).where(gender: "Masculino").count
      @requests_female = Request.where(created_at: @start_date..@end_date).where(campaign_id: params[:campaign]).where(gender: "Feminino").count
      @requests_not = Request.where(created_at: @start_date..@end_date).where(campaign_id: params[:campaign]).where(gender: "").count
      @type_user = Request.where(created_at: @start_date..@end_date).where(campaign_id: params[:campaign]).group(:gender).count
    elsif has_date?
      @requests = Request.where(created_at: @start_date..@end_date).group(:platform).count
      @requests_location = Request.where(created_at: @start_date..@end_date).group(:location).count
      @requests_total = Request.where(created_at: @start_date..@end_date).count
      @requests_male = Request.where(created_at: @start_date..@end_date).where(gender: "Masculino").count
      @requests_female = Request.where(created_at: @start_date..@end_date).where(gender: "Feminino").count
      @requests_not = Request.where(created_at: @start_date..@end_date).where(gender: "").count
      @type_user = Request.where(created_at: @start_date..@end_date).group(:gender).count
    elsif has_campaign?
      @requests = Request.where(campaign_id: params[:campaign]).group(:platform).count
      @requests_location = Request.where(campaign_id: params[:campaign]).group(:location).count
      @requests_total = Request.where(campaign_id: params[:campaign]).count
      @request_male = Request.where(campaign_id: params[:campaign]).where(gender: "Masculino").count
      @requests_female = Request.where(campaign_id: params[:campaign]).where(gender: "Feminino").count
      @requests_not = Request.where(campaign_id: params[:campaign]).where(gender: "").count
      @type_user = Request.where(campaign_id: params[:campaign]).group(:gender).count
    else
      @requests = Request.all.group(:platform).count
      @requests_location = Request.all.group(:location).count
      @requests_total = Request.all.count
      @requests_male = Request.all.where(gender: "Masculino").count
      @requests_female = Request.all.where(gender: "Feminino").count
      @requests_not = Request.all.where(gender: "").count
      @type_user = Request.all.group(:gender).count
    end

    if current_admin.administrador?
      @campaign = Campaign.all
    else
      @campaign = Campaign.where(admin_id: current_admin.id)
    end


    @array = @type_user.map do |name, data|
      if name == nil
        {name: "Não informado", data: data}
      elsif name == ""
        {name: "Fechou sem avisar", data: data}
      else
        {name: name, data: data}
      end
    end

    @devices = count_sistems(@requests)


    @requestsCSV = Request.where(created_at: @start_date..@end_date).where(campaign_id: params[:campaign])

    respond_to do |format|
      format.html
      format.csv { send_data @requestsCSV.to_csv }
    end
  end

  private

  def has_date?
    params[:start_date].present? and params[:campaign].blank?
  end

  def has_date_and_campaign?
    params[:start_date].present? and params[:campaign].present?
  end

  def has_campaign?
    params[:campaign].present? and params[:start_date].blank?
  end


  def set_dates
    @start_date = Date.parse(params[:start_date]) if params[:start_date].present?
    @end_date = Date.parse(params[:end_date]) if params[:start_date].present?
  end

  def count_sistems(request)
    hash = Hash.new
    hash[:android] = 0
    hash[:ios] = 0
    hash[:notebooks] = 0
    hash[:outros] = 0

    request.each do |device, users|
      if device.index(/android/i).present?
        hash[:android] += users
      elsif device.index(/ios/i).present?
        hash[:ios] += users
      elsif device.index(/macintosh/i).present? || device.index(/linux/i).present? || device.index(/windows/i).present? || device.index(/chrome/i).present?
        hash[:notebooks] += users
      else
        hash[:outros] += users
      end
    end

    hash
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
  def to_csv_not_relation(options = {}, data, titles)
    CSV.generate(options) do |csv|
      csv << titles
      data.each do |obj|
        csv << obj
      end
    end
  end
end

app/views/reports/devices.html.erb
<div class="row">
  <div class="col-xs-12">
    <section class="panel">
     

      <div class="panel-body" style="margin-top: -35px;">
        <div class="row state-overview">
              
        <div class="row">
          <div class="col-xs-12 well">
            <%= form_tag reports_devices_path, method: :get do %>
              <div class="row">
                <div class="form-group col-xs-3">
                  <%= label_tag 'Data inicial' %>
                  <%= text_field_tag :start_date, params[:start_date], class: 'form-control', id: 'start_date' %>
                </div>
                <div class="form-group col-xs-3">
                  <%= label_tag 'Data final' %>
                  <%= text_field_tag :end_date, params[:end_date], class: 'form-control', id: 'end_date' %>
                </div>
                <div class="form-group col-xs-3">
                  <%= label_tag 'Campanha' %>
                  <%= select_tag :campaign, content_tag(:option,'Selecione...',:value=>"")+options_from_collection_for_select(@campaign, "id", "name"), class: 'form-control', id: 'campaign' %>
                </div>


                <div class="col-xs-3">
                  <%= submit_tag 'Filtrar', class: 'btn btn-primary btn-filtrar' %>
                </div>
              </div>
            <% end %>
            <hr>
            <div class="col-lg-3 col-sm-3">
                  <section class="panel">
                      <div class="symbol terques">
                          <i class="fa fa-user"></i>
                      </div>

                      <div class="value">
                          <h1 style="font-size: 20px;" class="counter">
                            <%= @requests_total %>
                          </h1>
                          <p>Total de Views</p>
                      </div>
                  </section>
              </div>
              <div class="col-lg-3 col-sm-3">
                  <section class="panel">
                      <div class="symbol blue">
                          <i class="fa fa-male"></i>
                      </div>

                      <div class="value">
                          <h1 style="font-size: 20px;" class="counter">
                            <%= @requests_male %>
                          </h1>
                          <p>Total de Homens</p>
                      </div>
                  </section>
              </div>
              <div class="col-lg-3 col-sm-3">
                  <section class="panel">
                      <div class="symbol yellow">
                          <i class="fa fa-female"></i>
                      </div>

                      <div class="value">
                          <h1 style="font-size: 20px;" class="counter">
                            <%= @requests_female %>
                          </h1>
                          <p>Total de Mulheres</p>
                      </div>
                  </section>
              </div>
              <div class="col-lg-3 col-sm-3">
                  <section class="panel">
                      <div class="symbol red">
                          <i class="fa fa-ban"></i>
                      </div>

                      <div class="value">
                          <h1 style="font-size: 20px;" class="counter">
                            <%= @requests_not %>
                          </h1>
                          <p>Não informaram sexo</p>
                      </div>
                  </section>
              </div>

          </div>
          </div>
               
          <section>
          <div class="col-xs-12" >
            <div class="panel-heading">
              Locais 
            </div>
            <!--custom chart start-->
            <div class="custom-bar-chart" style="display: table; width: 100%;"  >
              <%= bar_chart @requests_location, chart: {
          type: 'bar',
          height: '100%'
          
        } ,plotOptions: {
          bar: {
            barHeight: '100%',
            distributed: true,
            horizontal: true,
            dataLabels: {
              position: 'top'
            }
          }
          
        }, title: 'Requisições por Local', theme: 'palette7',

        yaxis: {
              labels: {
          show: true,
          align: 'right',
          minWidth: 0,
          maxWidth: 200,
          style: {
              colors: [],
              fontSize: '11px',
              fontFamily: 'Helvetica, Arial, sans-serif',
              fontWeight: 300,
              cssClass: 'apexcharts-yaxis-label',
          },
          offsetX: 0,
          offsetY: 0,
          rotate: 0
        
      }
            },

        dataLabels: {
              style: {
      fontSize: '15px',
      colors: ['#000'],
      align: 'right',
      fontFamily: 'Helvetica, Arial, sans-serif',
      fontWeight: 'bold'
  }, offsetX: 35
            }

         %>
              
              
            </div>

            <!--custom chart end-->
          </div>

          </section>
          <section>
          <div class="col-xs-12" style="margin-top: 60px;">
            <div class="panel-heading">
              Gênero dos usuários
            </div>
            <!--custom chart start-->
            <div class="custom-bar-chart" style="display: table;  width: 100%;">
              
              <%= pie_chart @array, theme: 'palette7' %>

            </div>
            
            <!--custom chart end-->
          </div>
          </section>
          <div class="col-xs-12" style="margin-top: 60px;">
            <div class="panel-heading">
              Dispositivos
            </div>

            <!--custom chart start-->
            <div class="custom-bar-chart" style="display: table;  width: 100%;">
              <%= column_chart @devices, theme: 'palette7' %>
            </div>
            <!--custom chart end-->
          </div>
          <div class="col-xs-12">
            <span class="pull-right">
              <p>
                <%= link_to "Baixar CSV", reports_devices_path(format: "csv", start_date: params[:start_date], end_date: params[:end_date]) %>
              </p>
            </span>
            
          </div>
         
        </div>
      </div>
    </section>

  </div>
</div>




<script>
  $( function() {
    $("#start_date").datetimepicker({
      format: 'DD/MM/YYYY'
    });
    $("#end_date").datetimepicker({
      format: 'DD/MM/YYYY'
    });
  } );
</script>

app/views/reports/operating_sistems.html.erb
<div class="row">
  <div class="col-xs-12">
    <section class="panel">
      <div class="panel-heading">
        Sistemas operacioanais
      </div>

      <div class="panel-body">
        <div class="row">
          <div class="col-xs-12 well">
            <%= form_tag reports_operating_sistems_path, method: :get do %>
              <div class="row">
                <div class="form-group col-xs-3">
                  <%= label_tag 'Data inicial' %>
                  <%= text_field_tag :start_date, params[:start_date], class: 'form-control', id: 'start_date' %>
                </div>
                <div class="form-group col-xs-3">
                  <%= label_tag 'Data final' %>
                  <%= text_field_tag :end_date, params[:end_date], class: 'form-control', id: 'end_date' %>
                </div>
                <div class="col-xs-3">
                  <%= submit_tag 'Filtrar', class: 'btn btn-primary btn-filtrar' %>
                </div>
              </div>
            <% end %>
            <hr>
          </div>
          <div class="col-xs-12">
              <!--custom chart start-->
              <div class="custom-bar-chart">
                <%= column_chart @devices %>
              </div>
              <!--custom chart end-->
          </div>
          <div class="col-xs-12">
            <span class="pull-right">
              <p>
                <%= link_to "Baixar CSV", reports_operating_sistems_path(format: "csv", start_date: params[:start_date], end_date: params[:end_date]) %>
              </p>
            </span>
          </div>
          <div class="col-xs-12">
            <table class="table table-striped table-bordered table-hover" id="dynamic-table">
              <thead>
                <tr>
                  <th>Plataforma</th>
                  <th>Quantidade</th>
                </tr>
              </thead>

              <tbody>
                <% @requests.each do |request| %>
                  <tr>
                    <td><%= request[0] %></td>
                    <td><%= request[1] %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>

<script>
  $( function() {
    $("#start_date").datetimepicker({
      format: 'DD/MM/YYYY'
    });
    $("#end_date").datetimepicker({
      format: 'DD/MM/YYYY'
    });
  } );
</script>

app/views/reports/recurring_guests.html.erb
<div class="row">
  <div class="col-xs-12">
    <section class="panel">
      <div class="panel-heading">
        Dispositivos
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-xs-12">
            <span class="pull-right">
              <p>
                <%= link_to "Baixar CSV", reports_recurring_guests_path(format: "csv", start_date: params[:start_date], end_date: params[:end_date]) %>
              </p>
            </span>
          </div>
          <div class="col-xs-12">
            <table class="table table-striped table-bordered table-hover" >
              <thead>
                <tr>
                  <th>Usuário</th>
                  <th>Email</th>
                  <th>Visitas</th>
                </tr>
              </thead>

              <tbody>
                <% @usuarios.each do |obj| %>
                  <tr>
                    <td><%= obj.name %></td>
                    <td><%= obj.email %></td>
                    <td><%= obj.connections %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>
<script>
  $( function() {
    $("#start_date").datetimepicker({
      format: 'DD/MM/YYYY'
    });
    $("#end_date").datetimepicker({
      format: 'DD/MM/YYYY'
    });
  } );
</script>

app/views/reports/times_with_more_hits.html.erb
<div class="row">
  <div class="col-xs-12">

    <section class="panel">

      <div class="panel-heading">
        Horário com mais acessos
      </div>

      <div class="panel-body">
        <div class="row">
          <div class="col-xs-12 well">
            <%= form_tag reports_times_with_more_hits_path, method: :get do %>
              <div class="row">
                <div class="form-group col-xs-3">
                  <%= label_tag 'Data inicial' %>
                  <%= text_field_tag :start_date, params[:start_date], class: 'form-control', id: 'start_date' %>
                </div>
                <div class="form-group col-xs-3">
                  <%= label_tag 'Data final' %>
                  <%= text_field_tag :end_date, params[:end_date], class: 'form-control', id: 'end_date' %>
                </div>
                <div class="col-xs-3">
                  <%= submit_tag 'Filtrar', class: 'btn btn-primary btn-filtrar' %>
                </div>
              </div>
            <% end %>
            <hr>
          </div>
          <div class="col-xs-12">
              <!--custom chart start-->
              <div class="custom-bar-chart">
                <%= area_chart @requests %>
              </div>
              <!--custom chart end-->
          </div>
          <div class="col-xs-12">
            <span class="pull-right">
              <p>
                <%= link_to "Baixar CSV", reports_times_with_more_hits_path(format: "csv", start_date: params[:start_date], end_date: params[:end_date]) %>
              </p>
            </span>
          </div>
          <div class="col-xs-12">
            <table class="table table-striped table-bordered table-hover" id="dynamic-table">
              <thead>
                <tr>
                  <th>Horário</th>
                  <th>Quantidade</th>
                </tr>
              </thead>

              <tbody>
                <% @requests.each do |request| %>
                  <tr>
                    <td><%= request[0] %></td>
                    <td><%= request[1] %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>

    </section>
  </div>
</div>



<script>
  $( function() {
    $("#start_date").datetimepicker({
      format: 'DD/MM/YYYY'
    });
    $("#end_date").datetimepicker({
      format: 'DD/MM/YYYY'
    });
  } );
</script>

app/views/reports/unique_guests.html.erb
<div class="row">
  <div class="col-xs-12">
    <section class="panel">
      <div class="panel-heading">
        Requisições Únicas
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-xs-12 well">
            <%= form_tag reports_unique_guests_path, method: :get do %>
              <div class="row">
                <div class="form-group col-xs-3">
                  <%= label_tag 'Data inicial' %>
                  <%= text_field_tag :start_date, params[:start_date], class: 'form-control', id: 'start_date' %>
                </div>
                <div class="form-group col-xs-3">
                  <%= label_tag 'Data final' %>
                  <%= text_field_tag :end_date, params[:end_date], class: 'form-control', id: 'end_date' %>
                </div>
                <div class="col-xs-3">
                  <%= submit_tag 'Filtrar', class: 'btn btn-primary btn-filtrar' %>
                </div>
              </div>
            <% end %>
            <hr>
          </div>
          <div class="col-xs-12">
            <div class="custom-bar-chart">
              <%= area_chart @graph %>
            </div>
          </div>
          <div class="col-xs-12">
            <span class="pull-right">
              <p>
                <%= link_to "Baixar CSV", reports_unique_guests_path(format: "csv", start_date: params[:start_date], end_date: params[:end_date]) %>
              </p>
            </span>
          </div>
          <div class="col-xs-12">
            <table class="table table-striped table-bordered table-hover" id="dynamic-table">
              <thead>
              <tr>
                <th>Horário</th>
                <th>MAC</th>
                <th>Ponto de Acesso</th>
                <th>SSID da rede</th>
                <th>Platforma</th>
                <th>Dispositivo</th>
                <th>Navegador</th>
              </tr>
              </thead>

              <tbody>
              <% @requests.each do |request| %>
                <tr>
                  <td><%= request.created_at.strftime("%d/%m/%m %H:%M:%S") %></td>
                  <td><%= request.mac %></td>
                  <td><%= request.location %></td>
                  <td><%= request.ssid %></td>
                  <td><%= request.platform %></td>
                  <td><%= request.device %></td>
                  <td><%= request.browser %></td>
                </tr>
              <% end %>
              </tbody>
            </table>
            <%= paginate @requests %>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>

<script>
    $(function () {
        $("#start_date").datetimepicker({
            format: 'DD/MM/YYYY'
        });
        $("#end_date").datetimepicker({
            format: 'DD/MM/YYYY'
        });
    });
</script>